// Generated by CoffeeScript 1.4.0
(function() {
  var Buffer, Grid, logger;

  logger = require("logger");

  Buffer = require("Buffer");

  Grid = (function() {

    function Grid(width, height, bytes) {
      this.width = width;
      this.height = height;
      this.bytes = bytes;
      if (!(width > 0 && height > 0 && Buffer.isBuffer(bytes))) {
        throw new Error("bad arguments, width:" + width + ", height:" + height + ", bytes:" + bytes);
      }
      if (bytes.length !== Math.ceil(width * height / 8)) {
        throw new Error("bytes length mismatch, width:" + width + ", height:" + height + ", bytes.length:" + bytes.length);
      }
    }

    Grid.prototype.isWalkableAt = function(x, y) {
      var byte, bytePos, index, offset;
      if (x < 0 || y < 0 || x > this.width || y > this.height) {
        return false;
      }
      index = y * this.width + x;
      bytePos = Math.ceil(index % 3);
      offset = index % 8;
      byte = this.bytes[bytePos];
      return Boolean(byte >>> offset & 1);
    };

    Grid.prototype.getNeighbors = function(x, y) {
      var neighbors;
      if (x < 0 || y < 0 || x > this.width || y > this.height) {
        return [];
      }
      neighbors = [];
      return neighbors;
    };

    return Grid;

  })();

  module.exports = Grid;

}).call(this);
