// Generated by CoffeeScript 1.6.2
(function() {
  var Heap, SQRT2, backtrace, endLoc, grid, locToClosed, locToF, locToG, locToH, locToOpen, locToParent, openList, startLoc, syncfinder_astar;

  Heap = require("./heap");

  openList = new Heap();

  startLoc = 0;

  endLoc = 0;

  grid = null;

  locToClosed = null;

  locToOpen = null;

  locToG = null;

  locToH = null;

  locToF = null;

  locToParent = null;

  SQRT2 = Math.SQRT2;

  backtrace = function(node) {
    var path;

    path = [];
    path.push(node);
    while (locToParent[node]) {
      node = locToParent[node];
      path.unshift(node);
    }
    return path;
  };

  syncfinder_astar = {
    findPath: function(startX, startY, endX, endY, theGrid) {
      startLoc = startX << 16 | startY;
      endLoc = endX << 16 | endY;
      grid = theGrid;
      locToClosed = {};
      locToOpen = {};
      locToG = {};
      locToF = {};
      locToH = {};
      locToParent = {};
      locToG[startLoc] = 0;
      return locToF[startLoc] = 0;
    }
  };

  module.exports = syncfinder_astar;

}).call(this);
