// Generated by CoffeeScript 1.4.0
(function() {
  var fixtures;

  fixtures = {
    396: {
      height: 96,
      width: 88,
      blockdata: "eNqt00sOwiAQAFAMiy45AkfhZhZvVuNFmrBwi6uSSBgHhopUNLV1EjJvwWeG AEAVZuAzR5YZFDL0TapEifRvFJoxGxmOLAWuC6xFz3WDLlPWzMvEbnafOG4g X0H7O8Ud5tL+w8k+eaM75QZgKAdvYdekaFJWHAvtkgeH9F/IXZdpgIhvkhiY uiIDw+aJoBMh1kJ0hWneC4dImVIcWsIZ07mmY32DWMSp5oUYtzeQtoicCmFB 36ZaT2pmH+nvPwCGkSQB"
    },
    395: {
      height: 96,
      width: 64,
      blockdata: "eNqt0jFSxDAMBdDvcZEGMOUWDOIY22Wvwg223GJnrYrzcARXnCMzXMCli0yE JCcDBVAlzRvHlkaWLPLnN9P/tr1Nv1tXp+gsQPbfh4NvFCCYgG/M5qjRph6Y zEHkw/wUYZzvLABhSoBmGzgW5BlPQMXYcAGOoKYLPCNVnIAHJE+jiTZLN27y ixv4bBwDX8xreL+69zz3dfe2n8tPl8C31WzVzN+OrFW2wKQVD6beJNXAekPQ FHjQhHkKJWpnpMQShEmsNVJJ7N650WKOTZujUalRtT7FpilJoxtp45fejyzd Phbr95v56uPSQnR863x8TuRj7YPFOs/ix/xAfyCP23sY9tEf0xftNovw"
    },
    378: {
      height: 96,
      width: 64,
      blockdata: "eNqtkjFuwzAMRT+hwVOrjhmKqsfI5lylN+iYIYg49Tw9gqaew0AvoFGDYZak bCRD28laHkSRBPm/RP48c/qfbW/G31lXTsGxANnDh4M/FICMgD/MxlGrjZow GQeRL+O3CCPPVgCaIqDdBg7FYs9AxdhwBo5ITS94Qaw4AY+I3kYbbSydYSO/ OonfDUfis/FCnxfnA8/93nndj8s9F+LrymzTzDeOrFM24qQTD0bdJFZi3RBp Ih60YZ6oBFVGSigknMSkkZrE9s4tLcaxqThaFVuqplNo2jJpdUsq/NL1yNLZ bTG9P4xvbpcOovat/rhPyW3txmL1s3iaJ/QP8rT9h2Ef+vkB91iM8A=="
    }
  };

  module.exports = fixtures;

}).call(this);
