// Generated by CoffeeScript 1.6.3
(function() {
  var fixtures;

  fixtures = {
    396: {
      height: 96,
      width: 88,
      blockdata: "eNqt00sOwiAQAFAMiy45AkfhZhZvVuNFmrBwi6uSSBgHhopUNLV1EjJvwWeG AEAVZuAzR5YZFDL0TapEifRvFJoxGxmOLAWuC6xFz3WDLlPWzMvEbnafOG4g X0H7O8Ud5tL+w8k+eaM75QZgKAdvYdekaFJWHAvtkgeH9F/IXZdpgIhvkhiY uiIDw+aJoBMh1kJ0hWneC4dImVIcWsIZ07mmY32DWMSp5oUYtzeQtoicCmFB 36ZaT2pmH+nvPwCGkSQB"
    },
    395: {
      height: 96,
      width: 64,
      blockdata: "eNqt0jFSxDAMBdDvcZEGMOUWDOIY22Wvwg223GJnrYrzcARXnCMzXMCli0yE JCcDBVAlzRvHlkaWLPLnN9P/tr1Nv1tXp+gsQPbfh4NvFCCYgG/M5qjRph6Y zEHkw/wUYZzvLABhSoBmGzgW5BlPQMXYcAGOoKYLPCNVnIAHJE+jiTZLN27y ixv4bBwDX8xreL+69zz3dfe2n8tPl8C31WzVzN+OrFW2wKQVD6beJNXAekPQ FHjQhHkKJWpnpMQShEmsNVJJ7N650WKOTZujUalRtT7FpilJoxtp45fejyzd Phbr95v56uPSQnR863x8TuRj7YPFOs/ix/xAfyCP23sY9tEf0xftNovw"
    },
    378: {
      height: 96,
      width: 64,
      blockdata: "eNqtkjFuwzAMRT+hwVOrjhmKqsfI5lylN+iYIYg49Tw9gqaew0AvoFGDYZak bCRD28laHkSRBPm/RP48c/qfbW/G31lXTsGxANnDh4M/FICMgD/MxlGrjZow GQeRL+O3CCPPVgCaIqDdBg7FYs9AxdhwBo5ITS94Qaw4AY+I3kYbbSydYSO/ OonfDUfis/FCnxfnA8/93nndj8s9F+LrymzTzDeOrFM24qQTD0bdJFZi3RBp Ih60YZ6oBFVGSigknMSkkZrE9s4tLcaxqThaFVuqplNo2jJpdUsq/NL1yNLZ bTG9P4xvbpcOovat/rhPyW3txmL1s3iaJ/QP8rT9h2Ef+vkB91iM8A=="
    },
    32: {
      height: 160,
      width: 88,
      blockdata: "eNqV1L1uFDEQAODx+cAUJ9ymQDGPgEQDBWwe5SRegAdAZ6cKBRIpqYBHyBtk TzwIRkKi3dKAs2Zm/LdJLpHY4vTdnsdjz/ic0h2PB9AHqe5l6Jz+gxi2HjIj ABSm8RpFH3AvQ+d0nfJXG2DOOlXjrnPmzN87PwY40bMh6gCjioayqglGmYkz jSJUujEYnanHt0pkKk90SK2mF5I4g5bhCJfpBFLER4WYd9O4e9g4rOAV8jNN R/VxwolzzEfELQYYfKaJRIlUZgZbOCCxmMwEVNeXDlY2nVIIEixukMrm4Jkt FXRwhPRb5hOiZ1IxFvwKjReZdG7OOz91vu9cZWLpZ9ne0k6Jx/oORpETb3QK cmLCgiJNorOEIf2CJ8QPxHFs/MbEZslZusqoOAzT67iuNHEDZYCJmhmIpnNw jXZspKKDwrDhiqlnPudEk0lh2Kh1oZ3heOCugI2gO9UlHyuJn7JTdMIlb/55 pi8U/J/lASpnIJZpFY21c2e8RfzRhkyMvkVcCtJxGb4g3wHT4PSZYFJ+NeYd 3+Ceypz5w3GhiD87530lzG86X4O64qywQeau48XiM/GYPXCyEbdMi8Uea6zH gjHTVF4waWm6XCeuk1bdORRice2CvoUdZvJ4LphiQdOpJ1OpJuMLTylnTrzv 3HY+tamujG+E0vZr9JWQtoc4QONjZqkqkZsNrlF0qko52TpWhkYVd5V8Rwq+ NDV9P8A/lUP6W2nT78pUxnrijecfdUbNJw=="
    },
    15: {
      height: 160,
      width: 120,
      blockdata: "eNqd1T1u2zAUAODHMo06FGAPEJQ+gqcgQxBdxUfw6I3q5DFXyQ2iIIPHHKEs coAymwbB7Hvk459rG0kIRNEHS9QjH/no/buaadm31C1VI9d9hjZeE0dzliEe u00MAbzuEjv/2/suU/p778W2cOstpK6c8M8TZE7gXwcAMUfOgI9im0zDtUqc iCuZuEe5RaYfoHOycCRCH6mR0kGiwq4F9m4S8Sckv9vhH6wzscvpxzJT4EU/ ZAJxyF0hKa5ME6layjj8Q/ZHGaYLA9QvcyYGq+8LR6TEN1aZSjTEWc09D3S3 gRQlFPbMi0XifkWERLeC3Hof81M4FolH/k7mvnoWHmMuy7vuLC3ctOwPOLQs gWikKVQtZUvoW2pkFYl20LfsqoeVA3ma3QFxNaYYBqj7oVt68iKHcIzfmWPL IfIq8g4ibyOXzJhquGauIy+ZnODuOBdlCMTlWa4bCvcBdlPL+QTFQB9yaQbl yJOsjlEk6rG8S5vgif4LTpDwbzYPgZbI1HLjKnbTzaYiJr2hTbT82Tgl0nG2 GqbJjlPxMzNNBXOutwaI/Ufouee4YUTYoXTLpKBNy1BZIh1dbE0ZqlJkKOt4 UQ+Jii7yOlGHLX+Z2AfqEzQt/TtoUlSRnin+43yK4QCYebUHmpa9/4uD/YIi Cu1jQYavgcpvI9Uv4s5L5pu3t+J5z/sQTwJ7J55mLmlEQ9W5Ii2MQkzBAr5x vULaKp/+T10q8Vj21fIwyH3NHRf7QsqdZb6EAi5tPhjoSzVpAVScaM8Uznmh mnS6N5xzkLEdcEgjyj9f8XF1pv0Db+Bn4Q=="
    },
    9: {
      height: 160,
      width: 80,
      blockdata: "eNq91L1u3DAMAGAKCuBO9ZqhwN0jeOxU513yAslYpIhl3JItb9Bn8aFD+wid CgUZ0tGHFoHTCGZISaTd2j10qpf7fPqhTFFC/C/PWK7IioJRwaQfqnP5E7aN CDbSCqXIrqgrkgbzPcfzRuJ5M+Z43o7QZOHbJk/yLWkA465iYw+QB5DSdGOl okaDz7kb4C9RM9A0HrhfT6vuVJBU4riNI/oCg0+yOEQ1PWRhRTpjXfGUDKDY dRI9dZ9+X6+r+7uquZzOd1w3qq+iZljRs4q+18Y4nCqRK6MM61MWlHcpSaNJ GaS8UEJYG+x3osPnpJo1JvkipbXGzqakJ3GdvDNZ1bVoCFnmKQvv6eVL1ANJ iiYYr+qlcCfth6XamYyOzWUWjJupzuXoYikdRiq4WGj7KB68D5Bb259ZrTth FXjr4AQuo/jT31NrG/ep0d36F53yfvyh3/vNdr8TFSrrzkQ7t9St9Cs/ijaL 2qVofhH3ja7lmmSjPtAxsiF+Lu2vjTt9jl2x44J5ZfkozUStp1RASZXFwLpg 8XVE2ibhI0tOuN5KTm8lr0Kn8s0x9fWKNksNk/SKDJOKFdnlVTqTLh8ntUe1 V92t6LAifAF99IKj"
    }
  };

  module.exports = fixtures;

}).call(this);
