// Generated by CoffeeScript 1.3.3
(function() {
  var grid;

  grid = require("../grid");

  describe("Static method in Grid", function() {
    return it("should work", function() {
      var array2d, buf, height, i, width, _i, _ref, _results;
      array2d = [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 0]];
      width = 3;
      height = 5;
      buf = grid.bytesFrom2DArray(width, height, array2d);
      console.log(buf.toString('hex'));
      _results = [];
      for (i = _i = 0, _ref = buf.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push(console.log("[grid_test] buf[i]:" + (buf[i].toString(2))));
      }
      return _results;
    });
  });

}).call(this);
