// Generated by CoffeeScript 1.4.0
(function() {
  var Grid, array2d, buf, grid, height, width;

  Grid = require("../grid");

  array2d = [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 0]];

  width = 3;

  height = 5;

  buf = Grid.bytesFrom2DArray(width, height, array2d);

  grid = new Grid(width, height, buf);

  console.log("grid: " + grid);

  describe("Static method in Grid", function() {
    return it("should work", function() {
      var i, _i, _ref;
      for (i = _i = 0, _ref = buf.length; _i < _ref; i = _i += 1) {
        console.log("[grid_test] buf[i]:" + (buf[i].toString(2)));
      }
    });
  });

}).call(this);
