// Generated by CoffeeScript 1.6.3
(function() {
  var array2d, buf, grid, height, path, pathfinding, width;

  pathfinding = require("../../index");

  array2d = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [1, 1, 0, 0], [1, 0, 0, 0]];

  width = 4;

  height = 5;

  buf = pathfinding.bytesFrom2DArray(width, height, array2d);

  grid = pathfinding.buildGrid(width, height, buf);

  path = pathfinding.findPath(1, 0, 1, 4, grid);

  console.log("path:" + path);

  console.log("path on grid :" + (grid.toString(1 << 16 | 0, 1 << 16 | 4, path)));

}).call(this);
