// Generated by CoffeeScript 1.6.2
(function() {
  var Grid, countFailure, countSuccess, countTimes, data, fixture, grid, syncfinder_astar, totalMsSpent, zlib;

  Grid = require("../grid");

  fixture = require("./fixture");

  zlib = require('zlib');

  syncfinder_astar = require("../syncfinder_astar");

  data = fixture[378];

  console.dir(data);

  grid = null;

  countSuccess = 0;

  countFailure = 0;

  countTimes = 0;

  totalMsSpent = 0;

  zlib.inflate(new Buffer(data['blockdata'], 'base64'), function(err, buf) {
    if (err != null) {
      throw "FATAL...fail to inflate scene asset json";
      return;
    }
    grid = new Grid(data.width, data.height, buf);
    console.log("grid: " + grid);
    setInterval(function() {
      var end, msSpent, now, path, start;

      ++countTimes;
      while (true) {
        start = grid.getARandomWalkableBrick();
        end = grid.getARandomWalkableBrick();
        if (start !== end) {
          break;
        }
      }
      now = Date.now();
      path = syncfinder_astar.findPathByBrickLoc(start, end, grid);
      msSpent = Date.now() - now;
      if (path != null) {
        ++countSuccess;
      } else {
        ++countFailure;
      }
      totalMsSpent += msSpent;
      console.log("find path, ms spent:" + msSpent + ": path: " + (grid.toString(start, end, path)));
      console.log("Test times: " + countTimes + ", succeed:" + countSuccess + ", failed:" + countFailure + ", ms:" + msSpent + ", avg. ms:" + (totalMsSpent / countTimes));
    }, 500);
  });

  return;

}).call(this);
